const SPRITES = {
    
    floor_topLeft: 'assets/map/floor/top-left.png',
    floor_topOdd: 'assets/map/floor/top-odd.png',
    floor_topEven: 'assets/map/floor/top-even.png',
    floor_topRight: 'assets/map/floor/top-right.png',
    floor_rightOdd: 'assets/map/floor/right-odd.png',
    floor_rightEven: 'assets/map/floor/right-even.png',
    floor_bottomRight: 'assets/map/floor/bottom-right.png',
    floor_leftOdd: 'assets/map/floor/left-odd.png',
    floor_leftEven: 'assets/map/floor/left-even.png',
    floor_bottomLeft: 'assets/map/floor/bottom-left.png',
    floor_bottomOdd: 'assets/map/floor/bottom-odd.png',
    floor_bottomEven: 'assets/map/floor/bottom-even.png',
    floor_middleOdd: 'assets/map/floor/middle-odd.png',
    floor_middleEven: 'assets/map/floor/middle-even.png',
    zone: 'assets/map/zone/zone.png',
    wall_topLeft: 'assets/map/walls/top-left.png',
    wall_top: 'assets/map/walls/top.png',
    wall_topRight: 'assets/map/walls/top-right.png',
    wall_right: 'assets/map/walls/right.png', 
    wall_bottomRight: 'assets/map/walls/bottom-right.png',
    wall_bottom: 'assets/map/walls/bottom.png', 
    wall_bottomLeft: 'assets/map/walls/bottom-left.png', 
    wall_left: 'assets/map/walls/left.png', 
    wall_topLeftInner: 'assets/map/walls/top-left-inner.png',
    wall_topRightInner: 'assets/map/walls/top-right-inner.png',
    wall_bottomRightInner: 'assets/map/walls/bottom-right-inner.png',
    wall_bottomLeftInner: 'assets/map/walls/bottom-left-inner.png',
    door_top: 'assets/map/doors/bottom.png',
    door_bottom: 'assets/map/doors/top.png',
    door_right: 'assets/map/doors/right.png',
    door_left: 'assets/map/doors/left.png',
    soldier_walk_down_0: 'assets/map/characters/soldier/walk_down_0.png',
    soldier_walk_down_1:'assets/map/characters/soldier/walk_down_1.png',
    soldier_walk_down_2:'assets/map/characters/soldier/walk_down_2.png',
    soldier_walk_down_3:'assets/map/characters/soldier/walk_down_3.png',
    soldier_walk_up_0: 'assets/map/characters/soldier/walk_up_0.png',
    soldier_walk_up_1:'assets/map/characters/soldier/walk_up_1.png',
    soldier_walk_up_2:'assets/map/characters/soldier/walk_up_2.png',
    soldier_walk_up_3:'assets/map/characters/soldier/walk_up_3.png',
    soldier_walk_right_0: 'assets/map/characters/soldier/walk_right_0.png',
    soldier_walk_right_1:'assets/map/characters/soldier/walk_right_1.png',
    soldier_walk_right_2:'assets/map/characters/soldier/walk_right_2.png',
    soldier_walk_right_3:'assets/map/characters/soldier/walk_right_3.png',
    soldier_walk_left_0: 'assets/map/characters/soldier/walk_left_0.png',
    soldier_walk_left_1:'assets/map/characters/soldier/walk_left_1.png',
    soldier_walk_left_2:'assets/map/characters/soldier/walk_left_2.png',
    soldier_walk_left_3:'assets/map/characters/soldier/walk_left_3.png',
    soldier_idle_down_0: 'assets/map/characters/soldier/idle_down_0.png',
    soldier_idle_down_1:'assets/map/characters/soldier/idle_down_1.png',
    soldier_idle_down_2:'assets/map/characters/soldier/idle_down_2.png',
    soldier_idle_down_3:'assets/map/characters/soldier/idle_down_3.png',
    king: 'assets/map/characters/king/king.png',
    soldier_vs_soldier_background: 'assets/map/fight/fight_background.png',
    soldier_left_idle_0:'assets/map/fight/soldier_left/idle_0.png', 
    soldier_left_idle_1:'assets/map/fight/soldier_left/idle_1.png', 
    soldier_left_idle_2:'assets/map/fight/soldier_left/idle_2.png', 
    soldier_left_idle_3:'assets/map/fight/soldier_left/idle_3.png', 
    soldier_left_attack_high_0:'assets/map/fight/soldier_left/attack_0.png', 
    soldier_left_attack_high_1:'assets/map/fight/soldier_left/attack_1.png', 
    soldier_left_attack_high_2:'assets/map/fight/soldier_left/attack_high_2.png', 
    soldier_left_attack_high_3:'assets/map/fight/soldier_left/attack_3.png', 
    soldier_left_attack_low_0:'assets/map/fight/soldier_left/attack_0.png', 
    soldier_left_attack_low_1:'assets/map/fight/soldier_left/attack_1.png', 
    soldier_left_attack_low_2:'assets/map/fight/soldier_left/attack_low_2.png', 
    soldier_left_attack_low_3:'assets/map/fight/soldier_left/attack_3.png', 
    soldier_left_attack_medium_0:'assets/map/fight/soldier_left/attack_0.png', 
    soldier_left_attack_medium_1:'assets/map/fight/soldier_left/attack_1.png', 
    soldier_left_attack_medium_2:'assets/map/fight/soldier_left/attack_medium_2.png', 
    soldier_left_attack_medium_3:'assets/map/fight/soldier_left/attack_3.png', 
    soldier_left_defend_high_0:'assets/map/fight/soldier_left/defend_0.png', 
    soldier_left_defend_high_1:'assets/map/fight/soldier_left/defend_1.png', 
    soldier_left_defend_high_2:'assets/map/fight/soldier_left/defend_high_2.png',
    soldier_left_defend_high_3:'assets/map/fight/soldier_left/defend_3.png', 
    soldier_left_defend_medium_0:'assets/map/fight/soldier_left/defend_0.png', 
    soldier_left_defend_medium_1:'assets/map/fight/soldier_left/defend_1.png', 
    soldier_left_defend_medium_2:'assets/map/fight/soldier_left/defend_medium_2.png',
    soldier_left_defend_medium_3:'assets/map/fight/soldier_left/defend_3.png',
    soldier_left_defend_low_0:'assets/map/fight/soldier_left/defend_0.png', 
    soldier_left_defend_low_1:'assets/map/fight/soldier_left/defend_1.png', 
    soldier_left_defend_low_2:'assets/map/fight/soldier_left/defend_low_2.png',
    soldier_left_defend_low_3:'assets/map/fight/soldier_left/defend_3.png',
    
    soldier_right_idle_0:'assets/map/fight/soldier_right/idle_0.png', 
    soldier_right_idle_1:'assets/map/fight/soldier_right/idle_1.png', 
    soldier_right_idle_2:'assets/map/fight/soldier_right/idle_2.png', 
    soldier_right_idle_3:'assets/map/fight/soldier_right/idle_3.png', 
    soldier_right_attack_high_0:'assets/map/fight/soldier_right/attack_0.png', 
    soldier_right_attack_high_1:'assets/map/fight/soldier_right/attack_1.png', 
    soldier_right_attack_high_2:'assets/map/fight/soldier_right/attack_high_2.png', 
    soldier_right_attack_high_3:'assets/map/fight/soldier_right/attack_3.png', 
    soldier_right_attack_low_0:'assets/map/fight/soldier_right/attack_0.png', 
    soldier_right_attack_low_1:'assets/map/fight/soldier_right/attack_1.png', 
    soldier_right_attack_low_2:'assets/map/fight/soldier_right/attack_low_2.png', 
    soldier_right_attack_low_3:'assets/map/fight/soldier_right/attack_3.png', 
    soldier_right_attack_medium_0:'assets/map/fight/soldier_right/attack_0.png', 
    soldier_right_attack_medium_1:'assets/map/fight/soldier_right/attack_1.png', 
    soldier_right_attack_medium_2:'assets/map/fight/soldier_right/attack_medium_2.png', 
    soldier_right_attack_medium_3:'assets/map/fight/soldier_right/attack_3.png', 
    soldier_right_defend_high_0:'assets/map/fight/soldier_right/defend_0.png', 
    soldier_right_defend_high_1:'assets/map/fight/soldier_right/defend_1.png', 
    soldier_right_defend_high_2:'assets/map/fight/soldier_right/defend_high_2.png',
    soldier_right_defend_high_3:'assets/map/fight/soldier_right/defend_3.png', 
    soldier_right_defend_medium_0:'assets/map/fight/soldier_right/defend_0.png', 
    soldier_right_defend_medium_1:'assets/map/fight/soldier_right/defend_1.png', 
    soldier_right_defend_medium_2:'assets/map/fight/soldier_right/defend_medium_2.png',
    soldier_right_defend_medium_3:'assets/map/fight/soldier_right/defend_3.png',
    soldier_right_defend_low_0:'assets/map/fight/soldier_right/defend_0.png', 
    soldier_right_defend_low_1:'assets/map/fight/soldier_right/defend_1.png', 
    soldier_right_defend_low_2:'assets/map/fight/soldier_right/defend_low_2.png',
    soldier_right_defend_low_3:'assets/map/fight/soldier_right/defend_3.png',
    
}

module.exports = {
    SPRITES,
}
